### ISSUE TITLE
Tree Traversal & Iterator acting weird

### ISSUE THREAD

**Issue by khalidelboray** [khalidelboray/raku-cmark#1]
functions like [`cmark_node_next`](https://github.com/khalidelboray/raku-cmark/blob/master/lib/Cmark/Native.pm6#L158)
dose not return the next node and the thing happens with the Iterator  functions. i don't know if it's caused by the C lib or my binding

**Comment by JJ** [comment]
What do you mean exactly by *acting weird*? How does it fail?

**Comment by khalidelboray** [comment]
it returns NULL whether there is a node or not

**Comment by JJ** [comment]
An example?

**Comment by khalidelboray** [comment]
```perl6
use Cmark::Native;

my $md = q:to/MARK/;
# H1
* List 1
* List 2
    * List 1-1
    * List 1-2
MARK
my $node = cmark_parse_document($md,$md.codes,0);
put "Node Type is " ~ $node.type(:str);
put "First Doc child id of type : " ~ $node.first-child.type(:str);
put "Last Doc child id of type : " ~ $node.last-child.type(:str);
# This is the document , doing next on it returns node of type NULL
# looks like it was a miss understand, cuz it works on the heading node
put "Next doc node : " ~ $node.next.type(:str);
put "First child is: " ~ $node.first-child.type(:str);
put "Next node after Heading : " ~ $node.first-child.next.type(:str);
```
OUTPUT 

> Node Type is document
> First Doc child id of type : heading
> Last Doc child id of type : list
> Next doc node : NONE
> First child is: heading
> Next node after Heading : list

i will try the Iterator again with this in mind

**Comment by khalidelboray** [comment]
It seems that i didn't sleep the night i tested these things, every thing works as expected so i will continue working on the Iterator and the Custom renderer
