### ISSUE TITLE
NativeCall takes care of the extension

### ISSUE THREAD

**Issue by JJ** [khalidelboray/raku-cmark#2]
So you don't need to do this:

https://github.com/khalidelboray/raku-cmark/blob/d5a9262daa7fd7db6d60841bae0d233917d2bb7a/lib/Cmark/Native.pm6#L4

Which, besides, would fail for Mac OSX

**Comment by khalidelboray** [comment]
yes i thought i did something wrong here, but in my windows machine it fails if i just use `is native('cmark')`

**Comment by JJ** [comment]
But maybe it's because it's placed where Windows cannot find it... Theoretically it should be able to find it by name only with `is native('cmark')`

**Comment by khalidelboray** [comment]
in windows it works with `is native('libcmark')` without the `.dll` but keeps failing with `is native('cmark')` `Cannot locate native library '(null)': error 0x7e`

**Comment by khalidelboray** [comment]
will `is native('libcmark')`  work in other platforms ?

**Comment by khalidelboray** [comment]
[Travis Build](https://travis-ci.com/github/khalidelboray/raku-cmark/builds/171019007#L1) passes with `is native('libcmark')` 
can you confirm if this will work ?

**Comment by JJ** [comment]
No, it does not work in Ubuntu. It *should* work in Windows, anyway. If it
does not it's either an error or some configuration problem.

**Comment by khalidelboray** [comment]
66a1f6439bc69c4011ec57e09e7ca14d4d735445 i will test in another windows machine, so it's `is native('cmark')` for now

**Comment by khalidelboray** [comment]
So in the other windows machine changing the `dll` name to `cmark.dll` made `is native('cmark')` work. 
| OS Name                   	| OS Version               
|---------------------------	|---------------------------
| Microsoft Windows 10 Home 	| 10.0.19041 N/A Build 1904

**Comment by khalidelboray** [comment]
i think this can be closed now ?

**Comment by khalidelboray** [comment]
it seems that i missed this in docs [here](https://docs.raku.org/language/nativecall#Library_paths_and_names) , and it explains what happened in windows `When using the library name, the name is assumed to be prepended with lib and appended with .so (or just appended with .dll on Windows), and will be searched for in the paths in the LD_LIBRARY_PATH (PATH on Windows) environment variable.`
